### PR TITLE
Fixes sudo, UI, duplicate point plotting issues

### PR DESCRIPTION
**Pull request by byteit101**
__IMPORTANT:__ Please take note of the below checklist, especially the first two items.

# Pull Request Checklist

- [x] All pull requests must include the Contributor License Agreement (see below).
- [ ] Code should conform to the following:
    - [x] pep8 compliant with some exceptions (see pytest.ini)
    - [ ] 100% test coverage with pytest (with valid tests). If you have difficulty
      writing tests for the code, feel free to ask for help or submit the PR without tests.
    - [ ] Complete, correctly-formatted documentation for all classes, functions and methods.
    - [ ] documentation has been rebuilt with ``tox -e docs``
    - [ ] All modules should have (and use) module-level loggers.
    - [ ] **Commit messages** should be meaningful, and reference the Issue number
      if you're working on a GitHub issue (i.e. "issue #x - <message>"). Please
      refrain from using the "fixes #x" notation unless you are *sure* that the
      the issue is fixed in that commit.
    - [ ] Git history is fully intact; please do not squash or rewrite history.

## Contributor License Agreement

By submitting this work for inclusion in wifi-survey-heatmap, I agree to the following terms:

* The contribution included in this request (and any subsequent revisions or versions of it)
  is being made under the same license as the wifi-survey-heatmap project (the Affero GPL v3,
  or any subsequent version of that license if adopted by wifi-survey-heatmap).
* My contribution may perpetually be included in and distributed with wifi-survey-heatmap; submitting
  this pull request grants a perpetual, global, unlimited license for it to be used and distributed
  under the terms of wifi-survey-heatmap's license.
* I have the legal power and rights to agree to these terms.

# UI & Sudo & Duplicate Point fixes
I think the UI repainting is fully fixed here. I'm not confident of sudo/paplay yet.

## UI + Scan background thread
The scan method now launches a background thread, if not already launched, to do the work of scanning. This makes the UI interactive and keeps desktop environments happy. I had to setup a pubsub thread callback mechanism as the scan background thread wants to repaint and update the status.

## Sudo + paplay ding
This works, in some environments. I need to fix the other environments and/or document. Feedback appreciated. The UI drops permissions ASAP once it launches the scan subprocess. Communication is via JSON and a Scanner proxy object. Also a security win.

## Plotting duplicate points
Duplicate points cause fun patterns, but useless output. Now they are filtered out

### CODE REVIEW

**Comment by jantman** [comment]
Thanks so much, @byteit101 ! Once you feel this is ready and tested, I'll be happy to give it a spin on my machine and merge! Thank you SO much for this! I no longer use this project for work, which means I pretty much only use it if a friend or family member is moving house and wants to know where to put their access point. So... I very rarely use this project at all anymore. I'm deeply appreciative of the users who are keeping it going (and much improved).

**Comment by byteit101** [comment]
This seems to be working for me now. I didn't want to muck with the readme or changelog too much, but the pulseAudo issue and root issue both are only for non-docker environments.

I haven't tested in docker.

**Comment by byteit101** [comment]
I used this again last weekend without issues on a fresh install. Functionally, it's much better now! Is there anything else you want me to do? Most of the checkmarks left don't seem to apply to this project?

**Comment by jantman** [comment]
Thank you SO much for this!

**Comment by jantman** [comment]
This is released as 2.0.0 https://github.com/jantman/python-wifi-survey-heatmap/releases/tag/2.0.0 and is available on Docker Hub and GHCR.

**Pull request merged**
